### ISSUE TITLE
Unable to access NOAA ftp using binder

### ISSUE THREAD

**Issue by slawler** [Dewberry/pfra-hydromet#1]
Testing notebooks on binder, urllib & ftplib methods timing out when attempting to access Atlas 14  datasets on file server at ftp://hdsc.nws.noaa.gov/pub/hdsc/data/. 

@Tmodurr -Have you had similar issues with NOAA ftps running on remote servers?

**Comment by Tmodurr** [comment]
@slawler I need to do a better job seeing these. 

I've had issues with remote servers but mainly because it seems there are a bunch of domains that I've needed to get whitelisted (*.femadata.com). Not sure if these are just dying on you because of Dewberry network issues? 

I've had a fair amount of (new) issues with establishing remote connections with trusted/viable domains.

Tbfair IT has been quick to whitelist but it's generally been trial and error, more error on finding out new urls are blocked.
