### ISSUE TITLE
Unable to get PrecipData via FTP

### ISSUE THREAD

**Issue by ShaneMPutnam** [Dewberry/pfra-hydromet#15]
- Problem: In PrecipTable.ipynb, when data cannot be downloaded for a specific duration and recurrence interval, the final precipitation frequency table is incomplete. However, a complete table is needed to run EventsTable.ipynb.
- Solution: Any file that cannot be retrieved should be added to a list and the code should attempt to redownload that file at the end of the for-loop.

**Comment by clgarcia** [comment]
Shane, 
I have been running PrecipTable and have had no luck downloading a complete set of the precipitation tables from the NOAA ftp link. It will start downloading for a certain AOI and then randomly get caught up on one file and not proceed. Essentially it just freezes and fails to write the output folder. Is this related to the bug you posted? Could this be due to a versioning issue with some of the dependent python modules. Other colleagues can successfully run the PrecipTable, which is causing confusion. 

Thanks

**Comment by ShaneMPutnam** [comment]
It sounds to me like this might be another issue. In the issue above, the table is still written to the outputs folder, it is just missing data for specific durations/return frequencies since the ftp timed-out (I just fixed this issue with PR #16). For any duration/return frequency, are any values returned for your area of interest? If some values are being returned, then it shouldn't be a version issue. Could you please take a screenshot of any errors that are returned or where it is freezing and post? Are you running the tool on the same network as your colleagues? I believe that firewalls will sometimes block an ftp.

**Comment by clgarcia** [comment]
I am not running on the same network as other colleagues, we are in separate offices. There is no error message, the tool just gets hung up on random ftp files. For example, for one AOI the PrecipTable states that there are 30 files for each storm interval, which equates to 120 files-- and the tool will just stop at file 74. When I exit out of the precip table and return to the pfra-hydromet dashboard, it will say that the script is still running. It has done this for up to 3 hours and I eventually end up killing it a clearing the kernels. If it was a firewall issue, why would it let me download up to 74 and then just stop? Just to eliminate the firewall problem, I went to the ftp link, searched for the proceeding file, and was able to download it manually. I installed jupyter notebook with Anaconda and python 3. So there is no way that this is due to incorrect dependency modules?

**Comment by slawler** [comment]
@clgarcia Does it *always* fail precisely on the 74th file? 

I'm guessing this is caused by some interference with one of the servers involved --or-- an issue with one of the files. As Shane mentions, if it is working on some of the files and suddenly stops it is highly unlikely that it is an environment issue.  

You might try and isolate the problem by running a single duration at a time, for example remove all the durations but one in your list:

```python
durations = ['04d'] 
dur_names = ['96hr']
```

run the notebook, and see what the behavior is. If you can isolate the file that it trips up on, then it is probably a file issue. If you can run all single durations (e.g. get all 30 files processed) independently than it is most likely a server issue.

Please make sure you pull the changes from #16 before testing.

**Comment by clgarcia** [comment]
@slawler -- after some testing, it depends on what AOI and what interval it is. 

I tried another AOI/interval and it failed at file 5 during the 
durations = ['06h'] 
dur_names = ['06hr']

So I tried another AOI/interval and it failed at file 22
durations = ['04d'] 
dur_names = ['96hr']

Both intervals are supposed to download 30 files and each interval gets hung up on different files. Either way, the script will not successfully download a full 30 files. I cloned the newest directory yesterday morning. The weird thing is that my colleague can successfully run the precipTable from his office on my AOI's, but I cannot.

**Comment by ShaneMPutnam** [comment]
@clgarcia, the master branch of the pfra-hydromet repository was updated this morning with pull request #16 .  I will continue to make updates/improvements, so please fork the repository so that you can make sure you are always up-to-date. In general, forking the repository instead of making a clone is the best practice in this case since it will show you at the top of your fork if you are behind the master.

It still sounds to me like it might either be a problem with a network activity manager (this is what I meant by a firewall earlier) which is preventing you from repeatedly pinging the same server or with the server itself. If this keeps happening, you can modify the function that retrieves the files via ftp and builds the table so that it is two separate functions. The first function could download the files individually and skip any that fail to download and then try again after the other files have downloaded. The second function could build the table if all of the files download successfully. We are happy to accept pull requests from a forked branch if you make these changes.

Lastly, if you want to compare your libraries to your colleagues, you can run _conda list_  in your anaconda command prompt and have your colleague do the same.

**Comment by ShaneMPutnam** [comment]
The original issue is addressed with PR #16. @clgarcia, if you continue to have problems with retrieving files via ftp please create a new issue and we can reference back to this discussion.
